name: Build ISO
on:
    push:
        branches:
            - master
        paths-ignore:
            - 'README.md'
            - 'LICENSE'
            - '.gitignore'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3

        - name: Install dependencies
          run: sudo apt-get install make nasm gcc xorriso mtools

        - name: Build ISO
          run: make build

        - uses: actions/upload-artifact@v4
          with:
            name: KageOS
            path: bin/KageOS.iso